// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ReadItemGetResponse, ReadItem2TestGetResponse, EchoGrpcApiEchoGrpcPostData, EchoGrpcApiEchoGrpcPostResponse } from './types.gen';

export class DefaultService {
    /**
     * Read Item
     * @returns string Successful Response
     * @throws ApiError
     */
    public static readItemGet(): CancelablePromise<ReadItemGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/'
        });
    }
    
    /**
     * Read Item2
     * @returns string Successful Response
     * @throws ApiError
     */
    public static readItem2TestGet(): CancelablePromise<ReadItem2TestGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/test'
        });
    }
    
    /**
     * Echo Grpc
     * @param data The data for the request.
     * @param data.requestBody
     * @returns HelloReply Successful Response
     * @throws ApiError
     */
    public static echoGrpcApiEchoGrpcPost(data: EchoGrpcApiEchoGrpcPostData): CancelablePromise<EchoGrpcApiEchoGrpcPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/echo_grpc',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}