// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type HelloReply = {
    message?: string;
};

export type HelloRequest = {
    name?: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ReadItemGetResponse = string;

export type ReadItem2TestGetResponse = string;

export type EchoGrpcApiEchoGrpcPostData = {
    requestBody: HelloRequest;
};

export type EchoGrpcApiEchoGrpcPostResponse = HelloReply;

export type $OpenApiTs = {
    '/': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: string;
            };
        };
    };
    '/test': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: string;
            };
        };
    };
    '/api/echo_grpc': {
        post: {
            req: {
                requestBody: HelloRequest;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: HelloReply;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
};